version: "3.8"

services:
  mongodb:
    image: mongo
    command: mongod --port 8003
    container_name: mongoDB
    network_mode: host
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - data.mongo.db:/data/db
    restart: always

volumes:
  data.mongo.db:
    name: "data.webMuffins.mongo.db"
